#!/usr/bin/env python
import sys

def print_usage():
	print 'Usage: fossilshadow [repo] [bare-repo-name]'

def main(argv):
	if len(argv) < 3:
		print_usage()
		sys.exit(1)

	repo_path = argv[1]
	bare_repo_path = argv[2]

if __name__ == '__main__':
	main(sys.argv)
